# file: app/config/config.yml
imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: include/assetic.yml }
    - { resource: include/fos.yml }
    - { resource: include/sonata/block.yml }
    - { resource: include/sonata/admin.yml }
    - { resource: include/sonata/doctrine_orm_admin.yml }
    - { resource: include/sonata/user.yml }
    - { resource: include/swiftmailer.yml }
    - { resource: include/doctrine_extensions.yml }
    - { resource: include/shtumi_useful_autocomplete.yml }
    - { resource: include/ali_datatable.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - ':Form:ixoil.html.twig'
            - 'IxoilJVectorMapBundle:Form:jvectormap.html.twig'
            - ShtumiUsefulBundle::fields.html.twig

# CodingfogeyFontAwesomeBundle Configuration
codingfogey_font_awesome:
    assets_dir: %kernel.root_dir%/../vendor/fortawesome/font-awesome
    filter: less
    customize:
        variables_file:         %kernel.root_dir%/Resources/less/fontawesome.variables.less
        font_awesome_output:    %kernel.root_dir%/Resources/less/fontawesome.less
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# BraincracftedBundle Configuration
braincrafted_bootstrap:
    auto_configure:
        assetic: false

# WhiteOctoberBreadcrumbsBundle Configuration
white_october_breadcrumbs:
    translation_domain: menu
    viewTemplate: 'IxoilCoreBundle:Menu:breadcrumbs.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        unix_socket: %database_socket%
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

jms_security_extra:
    expressions: true
    
# Ixoil bundles configuration
ixoil_cms:
    contact:
        sender: %contact_email%