assetic:
    debug:          %kernel.debug%
    use_controller: false
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        yui_css:
            jar: "%kernel.root_dir%/../vendor/nervo/yuicompressor/yuicompressor.jar"
        yui_js:
            jar: "%kernel.root_dir%/../vendor/nervo/yuicompressor/yuicompressor.jar"
        less:
            node: %node_assetic%
            node_paths: %node_paths_assetic%
            #compress: true
        lessphp:
            file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
            #formatter: "compressed"
            #preserve_comments: false
    assets:
        bootstrap_css:
            filters:
                - less
                - cssrewrite
                - yui_css
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/less/bootstrap.less
                #- %kernel.root_dir%/../vendor/jasny/bootstrap/less/jasny-bootstrap.less
                - %kernel.root_dir%/Resources/less/jasny-bootstrap.less
            output: min/bootstrap.min.css
        bootstrap_js:
            filters:
                - yui_js
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/transition.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/alert.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/button.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/carousel.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/collapse.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/dropdown.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/modal.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/tooltip.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/popover.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/scrollspy.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/tab.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/affix.js
                - %kernel.root_dir%/../vendor/jasny/bootstrap/js/fileinput.js
                - %kernel.root_dir%/../vendor/jasny/bootstrap/js/inputmask.js
                - %kernel.root_dir%/../vendor/jasny/bootstrap/js/offcanvas.js
                - %kernel.root_dir%/../vendor/jasny/bootstrap/js/rowlink.js
            output: min/bootstrap.min.js
        fontawesome_css:
            filters:
                - lessphp
                - cssrewrite
                - yui_css
            inputs:
                - %kernel.root_dir%/Resources/less/fontawesome.less
                #- %kernel.root_dir%/../vendor/fortawesome/font-awesome/less/font-awesome.less
            output: min/fontawesome.min.css
        theme_css:
            filters:
                - lessphp
                - cssrewrite
                #- yui_css
            inputs:
                - %kernel.root_dir%/Resources/public/css/animate.less
                - %kernel.root_dir%/Resources/public/css/font.css
                - %kernel.root_dir%/Resources/less/app.less
                #- %kernel.root_dir%/Resources/public/css/landing.css
            output: min/theme.min.css
        theme_js:
            filters:
                - yui_js
            inputs:
                - %kernel.root_dir%/Resources/public/js/app.js
                - %kernel.root_dir%/Resources/public/js/app.plugin.js
                - %kernel.root_dir%/Resources/public/js/landing.js
            output: min/theme.min.js
        theme_fuelux_css:
            filters:
                - cssrewrite
                - yui_css
            inputs:
                - %kernel.root_dir%/Resources/public/js/fuelux/fuelux.css
            output: min/theme.fuelux.min.css
        theme_fuelux_js:
            filters:
                - yui_js
            inputs:
                - %kernel.root_dir%/Resources/public/js/fuelux/fuelux.js
            output: min/theme.fuelux.min.js
        theme_bootstrap_filestyle_js:
            filters:
                - yui_js
            inputs:
                - %kernel.root_dir%/Resources/public/js/file-input/bootstrap-filestyle.min.js
            output: min/theme.bootstrap-filestyle.min.js
        theme_jvectormap_css:
            filters:
                - cssrewrite
                - yui_css
            inputs:
                - %kernel.root_dir%/Resources/public/js/jvectormap/jquery-jvectormap-1.2.2.css
            output: min/theme.jvectormap.min.css

        theme_jvectormap_js:
            filters:
                - yui_js
            inputs:
                - %kernel.root_dir%/Resources/public/js/jvectormap/jquery-jvectormap-1.2.2.min.js                
                - %kernel.root_dir%/Resources/public/js/jvectormap/jquery-jvectormap-fr-merc-en.js
            output: min/theme.jvectormap.min.js
            
        theme_charts_js:
            filters:
                - yui_js
            inputs: 
                - %kernel.root_dir%/Resources/public/js/charts/flot/jquery.flot.min.js   
                - %kernel.root_dir%/Resources/public/js/charts/flot/jquery.flot.tooltip.min.js
                - %kernel.root_dir%/Resources/public/js/charts/flot/jquery.flot.resize.js
                - %kernel.root_dir%/Resources/public/js/charts/flot/jquery.flot.orderBars.js               
                - %kernel.root_dir%/Resources/public/js/charts/flot/jquery.flot.pie.min.js               
                - %kernel.root_dir%/Resources/public/js/charts/flot/jquery.flot.grow.js               
                - %kernel.root_dir%/Resources/public/js/charts/flot/jquery.flot.time.js               
                #- %kernel.root_dir%/Resources/public/js/charts/flot/demo.js

                - %kernel.root_dir%/Resources/public/js/charts/easypiechart/jquery.easy-pie-chart.js

                - %kernel.root_dir%/Resources/public/js/charts/sparkline/jquery.sparkline.min.js
            output: min/theme.charts.min.js

        theme_datatables_css:
            filters:
                - cssrewrite
                - yui_css
            inputs:
                - %kernel.root_dir%/Resources/public/js/datatables/datatables.css
            output: min/theme.datatables.min.css

        theme_datatables_js:
            filters:
                - yui_js
            inputs:
                - %kernel.root_dir%/Resources/public/js/datatables/jquery.dataTables.min.js
            output: min/theme.datatables.min.js

        theme_calendar_css:
            filters:
                - cssrewrite
                - yui_css
            inputs:
                - %kernel.root_dir%/Resources/public/js/calendar/bootstrap_calendar.css
            output: min/theme.calendar.min.css

        theme_calendar_js:
            filters:
                - yui_js
            inputs:
                - %kernel.root_dir%/Resources/public/js/calendar/bootstrap_calendar.js
            output: min/theme.calendar.min.js
            
        theme_progressbar_css:
            filters:
                - cssrewrite
                - yui_css
            inputs:
                - %kernel.root_dir%/Resources/public/js/progressbar/bootstrap-progressbar-3.0.0-rc2.css
            output: min/theme.progressbar.min.css
            
        theme_progressbar_js:
            filters:
                #- yui_js
            inputs:
                - %kernel.root_dir%/Resources/public/js/progressbar/bootstrap-progressbar.js
            output: min/theme.progressbar.min.js

        jquery_js:
            filters:
                - yui_js
            inputs:
                - %kernel.root_dir%/../vendor/components/jquery/jquery.js
                - %kernel.root_dir%/Resources/public/js/jquery-ui-1.10.3.custom.min.js
                - %kernel.root_dir%/Resources/public/js/jquery.ui.touch-punch.min.js
                - %kernel.root_dir%/Resources/public/js/appear/jquery.appear.js
                - %kernel.root_dir%/Resources/public/js/slimscroll/jquery.slimscroll.min.js
            output: min/jquery.min.js

        ie_js:
            filters:
                - yui_js
            inputs:
                - %kernel.root_dir%/Resources/public/js/ie/html5shiv.js
                - %kernel.root_dir%/Resources/public/js/ie/respond.min.js
                - %kernel.root_dir%/Resources/public/js/ie/excanvas.js
            output: min/ie.min.js